#
# Perform a regular build on any branch except main

name: build

on:
  push:
    branches-ignore:
    - main

env:
  PYTHON_VERSION: 3.13.7

jobs:
  version:
    uses: ./.github/workflows/version.yml

  build:
    runs-on: ubuntu-latest
    needs: version
    env:
      MRMAT_VERSION: ${{ needs.version.outputs.version }}
    steps:

    - name: Checkout out our code
      uses: actions/checkout@v4

    - name: Set up uv and Python
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Test
      run: |
        uv run --frozen pytest
        python -m mypy --no-incremental --non-interactive --junit-xml ${GITHUB_WORKSPACE}/build/mypy.xml ${GITHUB_WORKSPACE}/src/mhpython || true 

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: ${{ always() }}
      with:
        name: Test and Coverage
        path: |
          build/mypy.xml
          build/junit.xml
          build/coverage.xml

    - name: Build
      run: |
        uv build --wheel
