#
# Perform a regular build on any branch except main

name: build

on:
  push:
    branches-ignore:
    - main

env:
  PYTHON_VERSION: 3.13.7

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MRMAT_VERSION: ${{ needs.version.outputs.version }}
    steps:

    - name: Checkout out our code
      uses: actions/checkout@v4

    - name: Set up uv and Python
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Version the project
      id: version
      uses: MrMatAP/mrmat-versioning-action@1.0.7
      with:
        ecosystem: python
        major: 1
        minor: 1

    - name: Test
      run: uv run --frozen pytest

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: ${{ always() }}
      with:
        name: Test
        path: build/junit.xml

    - name: Build
      env:
        MRMAT_VERSION: ${{ steps.version.outputs.version }}
      run: |
        uv build --wheel
