name: Qodana
on:
  workflow_dispatch:
  # Block a merge into main unless we pass the quality gate
  pull_request:
    branches:
      - main
  push:
    branches:
      - develop
      - feature/qodana

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2022.3.0
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
        with:
          args: -i,src
          upload-result: false

      - uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json
